# Dicts that match codes to the labels in data.

activity_codes = {
    210: "Full-time education - school sixth-form",
    220: "Full-time education - sixth-form college",
    230: "Full-time education - further education",
    240: "Full-time education - higher education",
    250: "Part-time education",
    260: "Gap year students",
    270: "Full-time education - other",
    280: "Special post-16 institution",
    290: "Full-time education :custodial institution (juvenile offender)",
    310: "Apprenticeship",
    320: "Full-time employment with study (regulated qualification)",
    330: "Employment without training",
    340: "Employment with training (other)",
    350: "Temporary employment",
    360: "Part-time employment",
    380: "Self-employment",
    381: "Self-employment with study (regulated qualification)",
    550: "Work not for reward with study (regulated qualification)",
    410: "ESFA funded work-based learning",
    430: "Other training",
    440: "DWP training and support programme",
    450: "Traineeship",
    460: "Supported Internship",
    530: "Re-engagement provision",
    540: "Working not for reward",
    610: "Not yet ready for work or learning",
    615: "Start date agreed (other)",
    616: "Start date agreed (RPA compliant)",
    619: "Seeking employment, education or training",
    620: "Not available to labour market/learning - carer",
    630: "Not available to labour market/learning - teenage parent",
    640: "Not available to labour market/learning - illness",
    650: "Not available to labour market/learning - pregnancy",
    660: "Not available to labour market/learning - religious grounds",
    670: "Not available to labour market/learning - unlikely ever to be economically active",
    680: "Not available to labour market/learning - other reason",
    710: "Custody (young adult offender)",
    810: "Current situation not known",
    820: "Cannot be contacted - no current address",
    830: "Refused to disclose activity",
}

activity_codes_higher_level = {
    210: "Education",
    220: "Education",
    230: "Education",
    240: "Education",
    250: "Education",
    260: "Education",
    270: "Education",
    280: "Education",
    290: "Education",
    310: "Employment",
    320: "Employment",
    330: "Employment",
    340: "Employment",
    350: "Employment",
    360: "Employment",
    380: "Employment",
    381: "Employment",
    550: "Employment",
    410: "Training",
    430: "Training",
    440: "Training",
    450: "Training",
    460: "Training",
    530: "Re-engagement activites",
    540: "NEET",
    610: "NEET",
    615: "NEET",
    616: "NEET",
    619: "NEET",
    620: "NEET",
    630: "NEET",
    640: "NEET",
    650: "NEET",
    660: "NEET",
    670: "NEET",
    680: "NEET",
    710: "Other",
    810: "Situation unknown",
    820: "Situation unknown",
    830: "Situation unknown",
}

ethnicity = {
    "WHI": "White British",
    "WHR": "Irish",
    "WHT": "Irish Traveller",
    "WHE": "Other European Origin",
    "WHO": "White - Other",
    "MXC": "White + Black Caribbean",
    "MXF": "White + Black African",
    "MXA": "White + Asian",
    "MXO": "Other Shared Heritage",
    "BLC": "Black  - Caribbean",
    "BLA": "Black - African",
    "BLO": "Black - Other",
    "IND": "Indian",
    "PAK": "Pakistani",
    "BAN": "Bangladeshi",
    "ASI": "Other Asian Origin",
    "CHI": "Chinese",
    "AOG": "Any Other Ethnic Origin",
    "AOA": "Arab",
    "X11": "~Info Not Obtained",
    "X12": "~Info Not Given",
    "X13": "~Refused to Provide",
    "WHG": "Gypsy/Roma",
    "AOA": "Arab",
    "BBRI": "Black British",
}


ks4_priorband_ptq_ee = {
    1: "below expected standard",
    2: "at expected standard",
    3: "higher standard",
    4: "Not available"
}

binary = {"Y": "Yes", "N": "No"}

gender = {"M": "Male", "F": "Female"}

senprovision = {"N": "No special education need", "K": "SEN Support", "E": "EHC plan"}

sentypes = {
    "SPLD": "Specifc Learning Difficulty",
    "MLD": "Moderate Learning Difficulty",
    "SLD": "Severe Learning Difficulty",
    "PMLD": "Profound & Mutiple Learning Difficulty",
    "SLCN": "Speech Language and Communication Needs",
    "HI": "Hearing Impairment",
    "VI": "Visual Impairment",
    "MSI": "Multi-Sensory Impairment",
    "PD": "Physical Disability",
    "ASD": "Autistic Spectrum Disorder",
    "OTH": "Other Difficulty/Disability",
    "SEMH": "Social, emotional and mental health",
    "NSA": "SEN support but no specialist assessment of type of need",
}

level_of_need = {
    1: "Intensive Support",
    2: "Extra Support",
    3: "Minimum Support",
}

characteristics = {
    "nccis_refugee_asylum_seeker": "Refugee/Asylum seeker",
    "nccis_substance_misuse": "Substance misuse (client disclosed)",
    "nccis_teenage_mother": "Teenage mother",
    "nccis_pregnancy": "Pregnant",
    "nccis_parent": "Parent",
    "nccis_care_leaver": "Care Leaver",
    "nccis_caring_for_own_child": "Caring for own child",
    "nccis_supervised_by_yots": "Supervised by YOT",
    "nccis_carer_not_own_child": "Carer not own child",
    "nccis_alternative_provision": "Alternative Provision",
    "nccis_looked_after_in_care": "Looked after / In care",
}
